events {
  worker_connections 1024;
}

stream {

  upstream pg_up {
    server pg-jakarta:5432;
  }


  upstream redis_up {
    server redis-master:6379;
  }

  server { listen 15432; proxy_pass pg_up; }
  server { listen 16379; proxy_pass redis_up; }
}